repos:
  - repo: https://github.com/psf/black
    rev: "27d20144a7517594e24a1649451177b2a11284be" # frozen: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "3298ddab3c13dd77d6ce1fc0baf97691430d84b0" # frozen: v4.3.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://github.com/pycqa/isort
    rev: "c5e8fa75dda5f764d20f66a215d71c21cfa198e1" # frozen: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/PyCQA/autoflake
    rev: "c056d7ffc63012a5c2eeda0143c535f439c8603f" # frozen: v2.0.0
    hooks:
      - id: autoflake
        args:
          [
            "-i",
            "--remove-duplicate-keys",
            "--remove-unused-variables",
            "--expand-star-imports",
            "--remove-all-unused-imports",
          ]